### ISSUE TITLE
CocoaPods could not find compatible version

### ISSUE THREAD

**Issue by priore** [SachinSabat/CheckJailBreakDevice#1]
Hi,
my pods like below:

platform :ios, '10.0'
target 'MyApp' do
  use_frameworks!
  pod 'CheckJailBreakDevice'
end

but when I run pod update it returns:

[!] CocoaPods could not find compatible versions for pod "CheckJailBreakDevice":
  In Podfile: CheckJailBreakDevice
Specs satisfying the `CheckJailBreakDevice` dependency were found, but they required a higher minimum deployment target.

**Comment by uniruddh** [comment]
@priore  You have to higher the deployment version in your project. Refer [this](https://stackoverflow.com/a/46467255/2571277) post for the reference.
